### ISSUE TITLE
[Question] regarding destination_floor format in `lci_rmf_adapter`

### ISSUE THREAD

**Issue by h-wata** [octarobotics/lci-rmf-adapter#1]
Thank you for the great project.

I have a question regarding the format of destination_floor in the code found here: https://github.com/octarobotics/lci-rmf-adapter/blob/dd2c45c78f9a4e37db250e67177df7e52de87364/lci_rmf_adapter/lci_rmf_adapter/lci_rmf_adapter.py#L282-L283

Currently, the destination_floor is specified as `<origination>:<destination>`, but OpenRMF's rmf_lift_supervisor sends it in the format of `<destination>`.

Should we modify the way destination_floor is specified? Is there a standard method in OpenRMF to handle this, or should we adjust the code to match either format?

For example, it is `/adapter_lift_requests` in my case,
```
---
lift_name: /lci/XXXXXXX/m/1
request_time:
  sec: 1721635460
  nanosec: 521667595
session_id: fleet_name/robot_name
request_type: 1
destination_floor: 27F
door_state: 2
```

Thanks for your help.
